aws_account_id         = "0000000000"
prefix                 = "hello"
ecr_repo_name          = "hello"
container_image_sha256 = "changeme"
github_repo_url        = "https://github.com/larstobi/spring-hello.git"
